"""Telegram WebApp initData HMAC-SHA256 validation.

Per Telegram docs (https://docs.telegram-mini-apps.com/platform/init-data):
- For HMAC validation, exclude ONLY the ``hash`` key from the data-check string.
- All other keys (including ``signature``, added in newer Bot API versions) MUST
  stay in the data-check string, otherwise the computed hash won't match.
"""

from __future__ import annotations

import hashlib
import hmac
import json
import logging
import time
from typing import Any
from urllib.parse import unquote

logger = logging.getLogger(__name__)


def verify_telegram_init_data(
    init_data: str,
    bot_token: str,
    *,
    max_age_seconds: int = 3600,
    now: int | None = None,
) -> dict[str, Any] | None:
    if not init_data or not bot_token:
        logger.warning("verify_telegram_init_data: empty init_data or bot_token")
        return None
    try:
        parsed = dict(item.split("=", 1) for item in init_data.split("&") if "=" in item)
        received_hash = parsed.pop("hash", None)
        if not received_hash:
            logger.warning("verify_telegram_init_data: no hash in init_data")
            return None

        data_check_string = "\n".join(f"{k}={unquote(v)}" for k, v in sorted(parsed.items()))
        secret_key = hmac.new(
            key=b"WebAppData",
            msg=bot_token.encode(),
            digestmod=hashlib.sha256,
        ).digest()
        expected_hash = hmac.new(
            key=secret_key,
            msg=data_check_string.encode(),
            digestmod=hashlib.sha256,
        ).hexdigest()

        if not hmac.compare_digest(expected_hash, received_hash):
            logger.warning(
                "verify_telegram_init_data: hash mismatch (keys in data: %s)",
                sorted(parsed.keys()),
            )
            return None

        # A valid HMAC can be replayed forever unless auth_date is checked.
        # Telegram sends auth_date as a Unix timestamp.  Allow a small amount
        # of clock skew, but reject missing, future and stale payloads.
        auth_date_raw = parsed.get("auth_date")
        if not auth_date_raw:
            logger.warning("verify_telegram_init_data: no auth_date in init_data")
            return None
        try:
            auth_date = int(unquote(auth_date_raw))
        except (TypeError, ValueError):
            logger.warning("verify_telegram_init_data: invalid auth_date")
            return None
        current_time = int(time.time()) if now is None else int(now)
        if auth_date > current_time + 30:
            logger.warning("verify_telegram_init_data: auth_date is in the future")
            return None
        if max_age_seconds > 0 and current_time - auth_date > max_age_seconds:
            logger.warning("verify_telegram_init_data: init_data expired")
            return None

        user_raw = parsed.get("user")
        if not user_raw:
            logger.warning("verify_telegram_init_data: no 'user' field in init_data")
            return None
        return json.loads(unquote(user_raw))
    except Exception:
        logger.exception("verify_telegram_init_data: unexpected error")
        return None


def verify_bot_auth_token(token: str, bot_token: str) -> dict[str, Any] | None:
    """Verify HMAC token generated by bot for mini-app auth."""
    if not token or not bot_token:
        return None
    try:
        parts = token.split(":")
        if len(parts) != 3:
            return None
        telegram_id_str, timestamp, received_mac = parts

        secret = hmac.new(
            key=b"WebAppData",
            msg=bot_token.encode(),
            digestmod=hashlib.sha256,
        ).digest()

        message = f"{telegram_id_str}:{timestamp}"
        expected_mac = hmac.new(
            key=secret,
            msg=message.encode(),
            digestmod=hashlib.sha256,
        ).hexdigest()

        if not hmac.compare_digest(expected_mac, received_mac):
            return None

        return {"id": int(telegram_id_str)}
    except Exception:
        return None


def verify_bot_link_token(token: str, bot_token: str) -> int | None:
    """
    Verify bot-generated HMAC token used in mini-app URL:
    {telegramId}_{expiry}_{hmac}.
    """
    if not token or not bot_token:
        return None
    try:
        parts = token.split("_", 2)
        if len(parts) != 3:
            return None

        telegram_id_str, expiry_str, received_sig = parts
        expiry = int(expiry_str)
        if int(time.time()) > expiry:
            return None

        data = f"{telegram_id_str}_{expiry_str}"
        expected_sig = hmac.new(
            bot_token.encode(),
            data.encode(),
            hashlib.sha256,
        ).hexdigest()

        if not hmac.compare_digest(expected_sig.lower(), received_sig.lower()):
            return None

        return int(telegram_id_str)
    except Exception:
        return None
